import fs from "node:fs/promises";
import vm from "node:vm";

const baseUrl = (process.argv[2] || "http://127.0.0.1:8787").replace(/\/$/, "");
const dataPath = new URL("../public/2_outputs/metrics/metrics_explorer_synthesized_data.js", import.meta.url);
const lexiconPath = new URL("../public/data/lexicon.json", import.meta.url);

const [dataSource, lexiconSource] = await Promise.all([
  fs.readFile(dataPath, "utf8"),
  fs.readFile(lexiconPath, "utf8"),
]);
const context = { window: {} };
vm.runInNewContext(dataSource, context);
const articles = context.window.GBLS_METRICS?.articles || [];
const lexicon = JSON.parse(lexiconSource);

const groupByNormalizedId = new Map(
  lexicon.map((group) => [group.id.toLowerCase(), group])
);

function recordFor(article) {
  const coding = {};
  for (const [normalizedId, group] of groupByNormalizedId) {
    const selected = new Set(String(article[normalizedId] || "").split("|").filter(Boolean));
    coding[group.id] = Object.fromEntries(
      group.items.map((item) => [item.id, selected.has(item.id)])
    );
  }
  return {
    articleId: article.article_id,
    usercode: "gpt5.5-i1",
    rubric: null,
    lexicon: coding,
    recordType: "prior_prompt_metadata",
    source: "1_coded_gbls_corpus_articles metadata generated by prior prompts",
  };
}

let next = 0;
let imported = 0;
const failures = [];
const workers = Array.from({ length: 10 }, async () => {
  while (next < articles.length) {
    const article = articles[next++];
    try {
      const response = await fetch(`${baseUrl}/api/codings`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(recordFor(article)),
      });
      if (!response.ok) throw new Error(`${response.status} ${await response.text()}`);
      imported += 1;
    } catch (error) {
      failures.push(`${article.article_id}: ${error.message}`);
    }
  }
});
await Promise.all(workers);

console.log(`Imported ${imported} prior-prompt metadata records as gpt5.5-i1.`);
if (failures.length) {
  console.error(failures.join("\n"));
  process.exitCode = 1;
}
